default:
  target: dev
  outputs:
    dev:
      type: databricks
      schema: default
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "/sql/1.0/warehouses/b1fcf80ad7899d1c"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 4

