default:
  target: dev
  outputs:
    dev:
      type: databricks
      schema: default
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "/sql/1.0/warehouses/YOUR_WAREHOUSE_ID"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 4

